- id: '1577603770683'
  alias: Turn off Living Room lights at bedtime
  description: ''
  trigger:
  - event: sunset
    offset: +05:15:00
    platform: sun
  condition:
  - condition: state
    entity_id: device_tracker.rosstaphone
    state: not_home
  action:
  - device_id: 0b6bb3b67d4e4af9b2db40dc2c98ba4d
    domain: light
    entity_id: light.corner_lamp
    type: turn_off
  - device_id: a88b6edcc3cb4ea8abd3b1eb6806ba8a
    domain: light
    entity_id: light.glass_lamp_in_kitchen
    type: turn_off
  - device_id: 5467c5da431642e49ea69a01feef1dc3
    domain: light
    entity_id: light.cabinet_strip
    type: turn_off
- id: '1578118457996'
  alias: Pi Status Warning
  description: ''
  trigger:
  - above: '75'
    entity_id: sensor.disk_use_percent
    platform: numeric_state
  - above: '80'
    below: '200'
    entity_id: sensor.memory_use_percent
    platform: numeric_state
  - above: '65'
    below: '200'
    entity_id: sensor.cpu_temperature
    platform: numeric_state
  condition: []
  action:
  - scene: scene.pi_status_warning
  - data:
      message: Pi Status Warning!
    service: notify.mobile_app_rosstaphone
- id: '1578127928222'
  alias: Ring Battery Warning
  description: ''
  trigger:
  - below: '20'
    entity_id: sensor.ring_front_door_battery
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Ring battery is low!
    service: notify.mobile_app_rosstaphone
- id: '1578128205516'
  alias: Alert if Front Door is unlocked when I leave
  description: ''
  trigger:
  - entity_id: device_tracker.rosstaphone
    event: leave
    platform: zone
    zone: zone.home
  condition:
  - condition: state
    entity_id: lock.front_door
    state: unlocked
  action:
  - data:
      message: The front door is unlocked! Attempting to lock...
    service: notify.mobile_app_rosstaphone
  - entity_id: lock.front_door
    service: lock.lock
- id: '1578128547014'
  alias: Alert if Front Door is unlocked at bedtime
  description: ''
  trigger:
  - at: '22:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: lock.front_door
    state: unlocked
  action:
  - data:
      message: The front door is unlocked! Attempting to lock...
    service: notify.mobile_app_rosstaphone
  - entity_id: lock.front_door
    service: lock.lock
- id: '1578200529912'
  alias: Alert if Porch light is off after sunset
  description: ''
  trigger:
  - event: sunset
    offset: +01:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: light.porch
    state: 'off'
  action:
  - data:
      message: The porch light is off! Turning on...
    service: notify.mobile_app_rosstaphone
  - entity_id: light.porch
    service: light.turn_on
- id: '1578205569884'
  alias: Alert if Porch light switch is off after sunset
  description: ''
  trigger:
  - event: sunset
    offset: +01:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: light.porch
    state: unavailable
  action:
  - data:
      message: The porch light switch is off!
    service: notify.mobile_app_rosstaphone
- id: '1578210817889'
  alias: Alert Power Outage
  description: ''
  trigger:
  - entity_id: light.study_bookshelf_lamp
    from: 'on'
    platform: state
    to: unavailable
  - entity_id: light.study_bookshelf_lamp
    from: 'off'
    platform: state
    to: unavailable
  condition: []
  action:
  - data:
      message: Possible Power Outage!
    service: notify.mobile_app_rosstaphone
- id: '1578634047736'
  alias: Alert if Garage is open when I leave
  description: ''
  trigger:
  - entity_id: device_tracker.rosstaphone
    event: leave
    platform: zone
    zone: zone.home
  condition:
  - condition: state
    entity_id: binary_sensor.wyzesense_garage_door
    state: 'on'
  action:
  - data:
      message: The garage door is open!
    service: notify.mobile_app_rosstaphone
- id: '1578634407098'
  alias: Alert if Garage is open at bedtime
  description: ''
  trigger:
  - at: '22:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.wyzesense_garage_door
    state: 'on'
  action:
  - data:
      message: The garage door is open!
    service: notify.mobile_app_rosstaphone
